name = "spunk-analytics"
main = "analytics.js"
compatibility_date = "2024-01-01"

# KV Namespace - create via:
# wrangler kv:namespace create ANALYTICS
# Then paste the id below:
[[kv_namespaces]]
binding = "ANALYTICS"
id = "6d37213cf0d14d008bd2ac79b0d2c1ab"
